name: Deploy node-investment-log-FE-react

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t otakuict/investment-log-fe  .

      - name: Publish Image to docker hub
        run: docker push otakuict/investment-log-fe:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull otakuict/investment-log-fe:latest
      - name: Delete old container
        run: docker rm -f investment-log-fe-container
      - name: Run Docker Container
        run: docker run -d -p 3001:3000 --name investment-log-fe-container  otakuict/investment-log-fe
