- name: Fix APT and install Nginx
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}  # e.g., ubuntu, ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    script_stop: true
    script: |
      set -euo pipefail
      export DEBIAN_FRONTEND=noninteractive

      # Refresh indexes
      sudo apt-get update -y

      # Repair any half-installed packages
      sudo dpkg --configure -a || true
      sudo apt-get -y -f install || true
      sudo apt-get -y --fix-broken install || true

      # (Optional) finish pending AWS kernel headers/tools if they caused the block
      sudo apt-get install -y linux-aws-headers-6.8.0-1029 linux-aws-tools-6.8.0-1029 || true

      # Try again to fix any remaining broken deps
      sudo apt-get -y --fix-broken install || true

      # Now install nginx cleanly
      sudo apt-get install -y nginx

      # Enable & start (no-op if already running)
      sudo systemctl enable nginx
      sudo systemctl restart nginx
